### PR TITLE
support text arrays

### PR DESCRIPTION
**Pull request by yannick**
not sure if this is all, i actually just tried writing

### CODE REVIEW

**Comment by IrenejMarc** [comment]
Should cover it, although I'm not sure updating the global oidForType makes sense, since it's already marked deprecated and will probably be completely removed with the next minor release.

I'll take a better look later. Thank you.

**Comment by yannick** [comment]
@IrenejMarc ok interesting, where is that noted, i couldn't find it

**Comment by IrenejMarc** [comment]
Just using the D `deprecated` thingy. Serialisers are the ones that need to provide Oids for the types they support now.
@yannick https://github.com/IrenejMarc/dpq/blob/c58e1279129e332e03ce4571f75c0ddaf8e89e0b/source/dpq/serialisation.d#L191

**Comment by IrenejMarc** [comment]
Also, when I have the time to write a test for this, or at least test it manually, I'll be making a new release. If nothing else, during the weekend.

**Pull request merged**
